
server:
  #配置端口号
  port: 8989
  servlet:
    #配置项目名
    context-path: /demo1
#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zyp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #设置当前应用环境为开发环境
  profiles:
    active: dev
mybatis-plus:
  configuration:
    #配置SQL执行日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置逻辑删除
  global-config:
    db-config:
      #逻辑删除的值为1
      logic-delete-value: 1
      #为逻辑删除的值为0
      logic-not-delete-value: 0

